version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
  pre_build:
    commands:
      - cd ./my-app
      - echo Installing python packages...
      - python -m venv .venv
      - . .venv/bin/activate
      - pip install -r requirements-test.txt
  build:
    commands:
      - echo run tests...
      - python -m pytest --junitxml=pytest_reports/junit.xml
      - python -m pytest

reports:
  pytest_reports:
    files:
      - junit.xml
    base-directory: ./my-app/pytest_reports
    file-format: JUNITXML
